### ISSUE TITLE
Environment variable SHMEM does not work

### ISSUE THREAD

**Issue by kabadisha** [dlandon/zoneminder.master-docker#15]
Hi Guys,
I've done some googling on this one and I think maybe this is a limitation imposed by docker that means you cant change the size of **/dev/shm** during runtime within the container.

[40_firstrun.sh tries to do this](https://github.com/dlandon/zoneminder.master-docker/blob/master/init/40_firstrun.sh#L327), but umount fails:
```
Setting shared memory to : 50% of 16277880 bytes
umount: /dev/shm: must be superuser to unmount.
mount: /dev/shm: permission denied.
```
I've tried to run the command manually to ensure I was root etc, but I get the same issue. As such, I think it may be a deliberate limitation imposed by Docker.

I had to increase the size of **/dev/shm** explicitly with this flag on the docker run command:`--shm-size="512m" \`

Has anyone else seen the same issue or have a different conclusion?
If not, I'll be happy to raise a PR to update the docs & remove the offending lines of code.

EDIT: Looks like someone else found the same issue: https://github.com/ZoneMinder/ZoneMinder/issues/1924

**Comment by dlandon** [comment]
Yes.  I need to change the documentation to show setting SHMEM="2G" or other memory size.  It's best to actually set a memory size and not a %.

**Comment by kabadisha** [comment]
Ok cool. I can do it if you like and raise a PR, save you a bit of effort :-)

**Comment by dlandon** [comment]
Already done.

**Comment by kabadisha** [comment]
You work fast!
Although, looking at the change - I'm not sure it will fix the issue.

Changing to a fixed value rather than a percentage won't stop the umount command from failing, so it will still fail to allocate the 2G.

Unless that issue is specific to my setup somehow?

Also we should probably update Readme.md too.
Honestly though, I've pestered you enough recently - let me raise a PR for a suggested change when I get a sec and we can review it at leisure. It's not a critical issue.

I'm just trying to iron out pesky errors in logs so I know they aren't actually causing other problems by proxy.
Sorry if it's disturbing your day.

Gotta go build some IKEA furniture right now, so will probably pick this back up later :-)

**Comment by dlandon** [comment]
It also seems to be associated with the privileged set to true on some systems.  Some users have suggested that I turn that off, but in my case, my cameras fail with it off.

Try turning off the privileged setting.  There will have to be more documented in the Readme once I understand a bit more about this issue.  I use this docker on my Unraid server and can't possibly test all the different docker hosts.  Windows seems to be the most troublesome.

**Comment by dlandon** [comment]
I can reproduce the the issue with privileged off and am working on a solution.

**Comment by kabadisha** [comment]
Oh, cool - I hadn't had a chance to try privileged on yet.

Couldn't we just use `--shm-size="2g" \` instead and remove the code where the container tries to adjust it since it wouldn't be needed any more?
The Docker docs seem to suggest that it is the primarily recommended way to do it. I can only assume it should work fine on an unraid host too...

**Comment by dlandon** [comment]
Yes, that's the thing to do.  I am testing and preparing a new release now.

**Comment by dlandon** [comment]
Everything updated.  A new docker was built.  Try now and see what you get.

ES 6.1.0 has been released.  I'll work on updating that next.

**Comment by kabadisha** [comment]
Thanks, will take a look a little later. Really appreciate you jumping on all these niggly things I am bothering you with - I hope it's not capitalising your time too much.

**Comment by dlandon** [comment]
This has been needing some attention.  Right now I have a little time and want to get this out of the way.

The master docker is updated with ES 6.1.0.  Should be good to go.  I'm going to update the production docker now.

**Comment by kabadisha** [comment]
Nice! I've just pulled the update on .master-docker and it seems to be working fine :-)

I didn't think you would go to the prod branch with Focal till it came out of alpha, but I guess it all seems fine so far :crossed_fingers:

I'll close this issue as resolved. Thanks!
