### ISSUE TITLE
MySQL Error after today Update

### ISSUE THREAD

**Issue by WumpE78** [dlandon/zoneminder.master-docker#17]
Hi dlandon,

i have replace localhost with 127.0.0.1, but error is the same.
i have upgraded from buil from 2020-11-18

her is the portainer log:

`BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 150.,
Compilation failed in require at /usr/bin/zmupdate.pl line 73.,
BEGIN failed--compilation aborted at /usr/bin/zmupdate.pl line 73.,
Jan  2 20:23:02 5fb74b240b21 zmupdate[1050]: ERR [Error reconnecting to db: errstr:Can't connect to MySQL server on '127.0.0.1' (111) error val:],
Starting ZoneMinder:,
DBI connect('database=zm;host=127.0.0.1','zmuser',...) failed: Can't connect to MySQL server on '127.0.0.1' (111) at /usr/share/perl5/ZoneMinder/Database.pm line 110.,
DBI connect('database=zm;host=127.0.0.1','zmuser',...) failed: Can't connect to MySQL server on '127.0.0.1' (111) at /usr/share/perl5/ZoneMinder/Database.pm line 110.,
Jan  2 20:23:02 5fb74b240b21 zmpkg[1060]: ERR [Error reconnecting to db: errstr:Can't connect to MySQL server on '127.0.0.1' (111) error val:],
DBI connect('database=zm;host=127.0.0.1','zmuser',...) failed: Can't connect to MySQL server on '127.0.0.1' (111) at /usr/share/perl5/ZoneMinder/Database.pm line 110.,
Jan  2 20:23:02 5fb74b240b21 zmpkg[1060]: ERR [Error reconnecting to db: errstr:Can't connect to MySQL server on '127.0.0.1' (111) error val:],
Unable to connect to DB. ZM Cannot continue.,
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 150.,
Compilation failed in require at /usr/share/perl5/ZoneMinder.pm line 33.,
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder.pm line 33.,
Compilation failed in require at /usr/bin/zmpkg.pl line 34.,
BEGIN failed--compilation aborted at /usr/bin/zmpkg.pl line 34.,
neMinder failed to start,
,
*** /etc/my_init.d/40_firstrun.sh failed with status 255,
,
*** Killing all processes...,
Jan  2 20:23:02 5fb74b240b21 syslog-ng[20]: syslog-ng shutting down; version='3.25.1',
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...,
*** Running /etc/my_init.d/05_set_the_time.sh...,
*** Running /etc/my_init.d/06_set_php_time.sh...,
*** Running /etc/my_init.d/07_set_dri_permissions.sh...,
Granting permissions on /dev/dri/* devices...,
*** Running /etc/my_init.d/10_syslog-ng.init...,
[2021-01-02T20:23:04.127612] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.25 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file; config-version='3.13',
[2021-01-02T20:23:04.138518] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;,
Jan  2 20:23:04 5fb74b240b21 syslog-ng[20]: syslog-ng starting up; version='3.25.1',
Jan  2 20:23:04 5fb74b240b21 syslog-ng[20]: WARNING: log-fifo-size() works differently starting with syslog-ng 3.22 to avoid dropping flow-controlled messages when log-fifo-size() is misconfigured. From now on, log-fifo-size() only affects messages that are not flow-controlled. (Flow-controlled log paths have the flags(flow-control) option set.) To enable the new behaviour, update the @version string in your configuration and consider lowering the value of log-fifo-size().;,
*** Running /etc/my_init.d/20_apt_update.sh...,
Performing updates...,
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease,
Hit:2 http://ppa.launchpad.net/iconnor/zoneminder-master/ubuntu focal InRelease,
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease,
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease,
Hit:5 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease,
Hit:6 http://security.ubuntu.com/ubuntu focal-security InRelease,
Reading package lists...,
Reading package lists...,
Building dependency tree...,
Reading state information...,
Calculating upgrade...,
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.,
Reading package lists...,
Building dependency tree...,
Reading state information...,
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.,
*** Running /etc/my_init.d/30_gen_ssl_keys.sh...,
using existing keys in "/config/keys",
*** Running /etc/my_init.d/40_firstrun.sh...,
Using existing conf folder,
le zm.conf already moved,
Moving zmeventnotification.ini,
Moving secrets.ini,
Moving opencv.sh,
Moving debug_opencv.sh,
Moving the event notification server,
Moving the pushover api,
Moving es_rules.json,
Using existing ssmtp folder,
Using existing mysql database folder,
Copy /config/control/ scripts to /usr/share/perl5/ZoneMinder/Control/,
Copy /config/conf/ scripts to /etc/zm/conf.d/,
Creating symbolink links,
usermod: no changes,
usermod: no changes,
usermod: no changes,
Using existing data directory for events,
Using existing data directory for images,
Using existing data directory for temp,
Using existing data directory for cache,
no crontab for root,
Installing machine learning modules & hooks...,
Tiny Yolo V3 files have already been downloaded, skipping...,
Yolo V3 files have already been downloaded, skipping...,
Tiny Yolo V4 files have already been downloaded, skipping...,
Yolo V4 files have already been downloaded, skipping...,
Moving objectconfig.ini,
Moving config_upgrade.py,
File zm_event_start.sh already moved,
File zm_event_end.sh already moved,
File zm_detect.py already moved,
File zm_detect_old.py already moved,
File zm_train_faces.py already moved,
File train_faces.py already moved,
Requirement already satisfied: face_recognition in /usr/local/lib/python3.8/dist-packages (1.3.0),
Requirement already satisfied: dlib>=19.7 in /usr/local/lib/python3.8/dist-packages (from face_recognition) (19.21.1),
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from face_recognition) (7.0.0),
Requirement already satisfied: face-recognition-models>=0.3.0 in /usr/local/lib/python3.8/dist-packages (from face_recognition) (0.3.0),
Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.8/dist-packages (from face_recognition) (7.1.2),
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from face_recognition) (1.19.4),
Hook installation completed,
Compiling opencv - this will take a while...,
Starting services...,
 * Starting Apache httpd web server apache2,
 * ,
 * Starting MariaDB database server mysqld,`

**Comment by dlandon** [comment]
Use the new docker run or compose and adjust shared memory until you see less than 50% of /dev/shm on the Zoneminder console.

**Comment by WumpE78** [comment]
this is my compose file since 1 year of your Image

version: '2'
services:
    zoneminder:
        container_name: Zoneminder
        image: dlandon/zoneminder.master:latest
        restart: unless-stopped
        ports:
            - 6802:6802/tcp
            - 18443:443/tcp
            - 19000:9150/tcp
        shm_size: '4gb'
        environment:
            - TZ=Europe/Berlin
            - PUID=99
            - PGID=100
            - INSTALL_HOOK=1
            - INSTALL_FACE=1
            - INSTALL_TINY_YOLOV3=1
            - INSTALL_YOLOV3=1
            - INSTALL_TINY_YOLOV4=1
            - INSTALL_YOLOV4=1
            - MULTI_PORT_START=0
            - MULTI_PORT_END=0
            - NO_START_ZM=0
        volumes:
            - /sharedfolders/docker/zoneminder:/config:rw
            - /sharedfolders/docker/zoneminder/data:/var/cache/zoneminder:rw
        networks: 
            - default
networks:
  default:
    external:
      name: local-web

i have now rebuild the container from your november image, this works fine

**Comment by WumpE78** [comment]
yesterday build is running fine.... thx
