### ISSUE TITLE
Funding to Develop New Docker and for Future Maintenance and Support

### ISSUE THREAD

**Issue by dlandon** [dlandon/zoneminder.master-docker#20]
We have set up a GoFundMe to fund the development of a new Docker that will be for Zoneminder and ES/ML with all the ES/ML modules pre-configured and for maintenance and support going forward.

[GoFundMe](https://www.gofundme.com/f/maintenance-of-zoneminder-docker-with-es-and-ml?utm_source=customer&utm_medium=copy_link&utm_campaign=p_cf+share-flow-1)

**Comment by mpraeger** [comment]
@dlandon Instead of using hub.docker.com why not give [GitHub's Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/) a try? That could avoid the issues mentioned in your GoFundMe post.

**Comment by dlandon** [comment]
This docker project is deprecated.
