### ISSUE TITLE
[Bug] Minor issue found in logrotate causing cron noise

### ISSUE THREAD

**Issue by Guyverix** [dlandon/zoneminder.master-docker#23]
Just wanted to let you know about a very MINOR issue with logrotate.  This is in the latest docker image.
Both utmp and btmp logrotate entries are duplicated, and causes logrotate to choke.

`root@b37b8118a6b4:/etc# cat logrotate.conf 
---- SNIP ---
/var/log/wtmp {
    missingok
    monthly
    create 0664 root utmp
    rotate 1
}
/var/log/btmp {
    missingok
    monthly
    create 0660 root utmp
    rotate 1
}
---- SNIP ----

in logrotate.d, both are already defined: (both btmp, and wtmp)
root@b37b8118a6b4:/etc# cat logrotate.d/btmp 
--- SNIP ----
/var/log/btmp {
    missingok
    monthly
    create 0660 root utmp
    rotate 1
}
`

**Comment by dlandon** [comment]
This docker project has been deprecated.
