### ISSUE TITLE
Cannot install docker image

### ISSUE THREAD

**Issue by bacevs** [dlandon/zoneminder.master-docker#26]
Following instructions to install:

The line: `docker pull dlandon/zoneminder.master`

Gives following error:
`Error response from daemon: pull access denied for dlandon/zoneminder.master, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

![dockererr](https://user-images.githubusercontent.com/1433845/146955770-a0fa783d-def4-4b11-a095-aa61c3384db4.jpg)

I tried manually looking for the repository and cannot seem to find it on your docker account
`https://hub.docker.com/u/dlandon`

**Comment by roobbb** [comment]
same here, even when I am logged in the access is denied 🙁
tried the other one "dlandon/zoneminder.machine.learning" - that is working, but on github its stated as deprecated

**Comment by dlandon** [comment]
The docker container is no longer available.
