### ISSUE TITLE
Issue with zmNinja v1.6 and Zoneminder-master v1.35.5 in latest Docker

### ISSUE THREAD

**Issue by sic79** [dlandon/zoneminder.master-docker#6]
"Event server version not supported. You are running version version 5.15.6-Docker. Please upgrade to version 6."

Since Pliable Pixels updated ES 6 and zmNinja to v1.6 this warning appears since the new version includes breaking changes.

**Comment by dlandon** [comment]
I've updated the docker and ES 6.  Please give it a try.

**Comment by sic79** [comment]
@dlandon Installed it now and the error is now gone in zmNinja, thanks :)

But, there is also a script that needs to be executed to convert old objectconfig.ini to newer format in ES 6 (variable name changes etc). I can´t see any changes in mine after the update so I assume you have not included that? 

Pliable Pixels wrote this:

"To help with this ‘big bad breaking change’, I’ve provided an upgrade script. When you run ./install.sh it will automatically run it at the end and put a migrated-objectconfig.ini in your current directory (from where you ran ./install.sh) You can also run it manually by invoking hook/config_upgrade.py -c /etc/zm/objectconfig.ini"

It should not be that hard even for a linux beginner to run the script manually since it´s just to copy/paste the commandline, so maybe it´s just extra work on your side to include that part?.

**Comment by dlandon** [comment]
I'll take care of it later today.

**Comment by dlandon** [comment]
I've updated the docker to run the config_upgrade.py script.  There are new configuration parameters you'll have to modify for ES 6.  Look in the objectconfig.ini file for #NEW tags and make changes appropriate for your system.

My reference to taking care of it today is the config_upgrade.py script.  I'll update the stable zoneminder docker once the issues on the master docker are sorted out.  I'd appreciate some patience here while I get through the testing,

**Comment by sic79** [comment]
It works fine now, the only thing that I did manually was to rename the obsolete names yolo to object and [ml] to [remote] in objectconfig.ini then the object detection worked again. Just as Pliable Pixels wrote:

"yolo is no longer used. Instead object is used. object could be multiple object detection techniques, yolo or otherwise.
[ml] is now [remote]"

I have not tried Face and Plate detection since I have not configure it on my setup, maybe someone else can confirm that it works for those also?

Thanks for a fast fix as usual @dlandon 👍

**Comment by hugalafutro** [comment]
Hi,
I created new `objectconfig.ini` manually by copying & editing `objectconfig.ini.default` and adding in my values yesterday after you published the image with updated eventserver and got the hooks working before you updated the image with the `config_upgrade.py` script today. After pulling todays image and recreating the container the hooks stopped working completely without producing any hook processing message in logs at all. I checked the .ini and it's the same it just added `version=1.1`.

I use `docker exec -it zoneminder sudo -u www-data /var/lib/zmeventnotification/bin/zm_event_start.sh [eventid] [monitorid]` to check the hooks are working. Previously even if misconfigured there would at least be the initial pause as defined by `wait=5` and the start of hook processing would be indicated in output of `docker-compose logs -f`.

I then went and deleted all the objectconfig.ini files, destroyed, pulled and recreated the container again, and edited the newly generated `objectconfig.ini` by deleting the example `[monitor-999]` and adding in my 2 monitors like so:

```
[monitor-1]
# front door
match_past_detections=no
wait=5
object_detection_pattern=(person)
detection_sequence=object

[monitor-2]
match_past_detections=no
wait=5
object_detection_pattern=(person)
detection_sequence=object
```

running `docker exec -it zoneminder sudo -u www-data /var/lib/zmeventnotification/bin/zm_event_start.sh [eventid] [monitorid]` now produces no output in logs whatsoever and immediately silently exits without even obeying the `wait=5`.

Possibly related, as I previously reported in https://github.com/dlandon/zoneminder.master-docker/issues/5 the hook models are not being downloaded so I had to copy in the yolo3 models manually.

related files:
objectconfig.ini: https://pastebin.com/raw/vK9KVS40
docker-compose.yml: https://pastebin.com/raw/UC0ahc55
docker-compose log from creating the container: https://pastebin.com/raw/s3n8gBZu

Any advice welcome, thanks!

**Comment by sic79** [comment]
I´m gonna try to rebuild the docker with yolo4 and try a fresh objectconfig.ini and see if it works, will take some time because building with gpu support. Will report back later today

**Comment by sic79** [comment]
Works fine. Well yolov4 not so much obviously, hopefully soon. But with yolov3 all is well. So I think this issue can be closed. Thanks!
