### ISSUE TITLE
Problem with installing zondeminder docker

### ISSUE THREAD

**Issue by jandorresteijn** [dlandon/zoneminder.master-docker#9]
Hi, I am trying to install zoneminder docker, but I get an error.

I already have an mysql running.

I hope you can help me.

Regards

Jan

Compilation failed in require at /usr/bin/zmupdate.pl line 73.
BEGIN failed--compilation aborted at /usr/bin/zmupdate.pl line 73.
Oct 28 11:45:09 23fd6bdf4a35 zmupdate[1153]: ERR [Error reconnecting to db: errstr:Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) error val:]
 * Starting Apache httpd web server apache2
 * 
Starting ZoneMinder:
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
Oct 28 11:45:11 23fd6bdf4a35 zmpkg[1189]: ERR [Error reconnecting to db: errstr:Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) error val:]
Unable to connect to DB. ZM Cannot continue.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 150.
Compilation failed in require at /usr/share/perl5/ZoneMinder.pm line 33.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder.pm line 33.
Compilation failed in require at /usr/bin/zmpkg.pl line 34.
BEGIN failed--compilation aborted at /usr/bin/zmpkg.pl line 34.
Oct 28 11:45:11 23fd6bdf4a35 zmpkg[1189]: ERR [Error reconnecting to db: errstr:Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) error val:]
ZoneMinder failed to start

*** /etc/my_init.d/40_firstrun.sh failed with status 255

*** Killing all processes...
Oct 28 11:45:11 23fd6bdf4a35 syslog-ng[16]: syslog-ng shutting down; version='3.13.2'

**Comment by FabriceC01** [comment]
Hello,
Same problem for me...
Fabrice

**Comment by dlandon** [comment]
I have added a new environment variable that will prevent MySql and Zoneminder from starting so the docker will stay running and you can go into the docker and troubleshoot.  Look at the readme for details.
